AllCops:
  Include:
    - '**/Rakefile'
    - '**/Guardfile'
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - 'Rakefile'
    - 'lib/bel_parser/parsers/expression/parameter.rb'
    - 'lib/bel_parser/parsers/expression/parameter.rl'
    - 'lib/bel_parser/parsers/expression/comment.rb'
    - 'lib/bel_parser/parsers/expression/comment.rl'
    - 'lib/bel_parser/parsers/expression/relationship.rb'
    - 'lib/bel_parser/parsers/expression/relationship.rl'
    - 'lib/bel_parser/parsers/expression/term.rb'
    - 'lib/bel_parser/parsers/expression/term.rl'
    - 'lib/bel_parser/parsers/expression/statement_observed_term.rb'
    - 'lib/bel_parser/parsers/expression/statement_observed_term.rl'
    - 'lib/bel_parser/parsers/expression/statement_simple.rb'
    - 'lib/bel_parser/parsers/expression/statement_simple.rl'
    - 'lib/bel_parser/parsers/expression/statement_nested.rb'
    - 'lib/bel_parser/parsers/expression/statement_nested.rl'
    - 'lib/bel_parser/parsers/bel_script/define_annotation.rb'
    - 'lib/bel_parser/parsers/bel_script/define_annotation.rl'
    - 'lib/bel_parser/parsers/bel_script/define_namespace.rb'
    - 'lib/bel_parser/parsers/bel_script/define_namespace.rl'
    - 'lib/bel_parser/parsers/bel_script/set.rb'
    - 'lib/bel_parser/parsers/bel_script/set.rl'
    - 'lib/bel_parser/parsers/bel_script/unset.rb'
    - 'lib/bel_parser/parsers/bel_script/unset.rl'
    - 'lib/bel_parser/parsers/common/blank_line.rb'
    - 'lib/bel_parser/parsers/common/blank_line.rl'
    - 'lib/bel_parser/parsers/common/common.rb'
    - 'lib/bel_parser/parsers/common/common.rl'
    - 'lib/bel_parser/parsers/common/identifier.rb'
    - 'lib/bel_parser/parsers/common/identifier.rl'
    - 'lib/bel_parser/parsers/common/string.rb'
    - 'lib/bel_parser/parsers/common/string.rl'
    - 'lib/bel_parser/parsers/common/list.rb'
    - 'lib/bel_parser/parsers/common/list.rl'
    - 'lib/bel_parser/parsers/common/comment_line.rb'
    - 'lib/bel_parser/parsers/common/comment_line.rl'
