require_relative 'expression/parameter'
require_relative 'expression/term'
require_relative 'expression/relationship'
require_relative 'expression/comment'
require_relative 'expression/observed_term'
require_relative 'expression/simple_statement'
require_relative 'expression/nested_statement'
